apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-files-demo
  labels:
    app: azure-files-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-files-demo
  template:
    metadata:
      labels:
        app: azure-files-demo
    spec:
      containers:
      - name: django-app
        image: acritalynorth01.azurecr.io/azure-files-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: azure-files-volume
          mountPath: /data
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: FILES_STORAGE_PATH
          value: "/data"
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          value: "django-production-secret-key-change-me"
        livenessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: azure-files-volume
        persistentVolumeClaim:
          claimName: azure-files-pvc
